services:
    postgres:
      image: 'postgres:latest'
      environment:
        - 'POSTGRES_DB=reader'
        - 'POSTGRES_USER=andrew'
        - 'POSTGRES_PASSWORD=gomes'
      ports:
        - "5432:5432"
    redis:
      image: 'redis:latest'
      ports:
        - '6379'