services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=reader'
      - 'POSTGRES_PASSWORD=gomes'
      - 'POSTGRES_USER=andrew'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'