version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: andrew
      MYSQL_DATABASE: reader
      MYSQL_USER: andrew
      MYSQL_PASSWORD: gomes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reader
      SPRING_DATASOURCE_USERNAME: andrew
      SPRING_DATASOURCE_PASSWORD: gomes
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./src:/app/src
      - ~/.m2:/root/.m2
    depends_on:
      - mysql
    command: ./mvnw spring-boot:run

volumes:
  mysql_data: